DimaZadrutsiy/DemoQA_JAVA

src/test/java/pages/Elements/ButtonsPage.java, src/test/java/pages/Elements/ElementsPage.java, src/test/java/tests/ElementsTests/ButtonTest.java, src/test/java/tests/ElementsTests/ElementsTest.java
Jira - https://fem22.atlassian.net/browse/DF-17?atlOrigin=eyJpIjoiMTdmNDc1YWU1ZGZjNDI4Yjg5MDRlMDdkZWExZDcwY2QiLCJwIjoiaiJ9
=> DF17_testCheckingMessagesWhenButtonsArePressed

src/test/java/pages/BasePage.java, src/test/java/pages/BookStoreApplication/BookStorePage.java, src/test/java/pages/BookStoreApplication/LoginPage.java, src/test/java/pages/BookStoreApplication/RegisterPage.java, src/test/java/tests/BookStoreApplicationTest.java
some refactoring + testLoginValidData_WithCaptcha, testBookStorePageSubMenuList are added
=> AT testLoginValidData_WithCaptcha, testBookStorePageSubMenuList are added

src/test/java/base/BaseTest.java, src/test/java/base/BaseUtils.java, src/test/java/pages/BasePage.java, src/test/java/pages/Elements/ElementsPage.java, src/test/java/tests/BookStoreApplicationTest/BookStoreApplicationTest.java, src/test/java/tests/BookStoreApplicationTest/LoginTest.java, src/test/java/tests/BookStoreApplicationTest/RegisterNewUserTest.java, src/test/java/tests/ElementsTests/ButtonTest.java, src/test/java/tests/ElementsTests/CheckBoxTest.java, src/test/java/tests/ElementsTests/ElementsTest.java, src/test/java/tests/FormsTests/FormsTest.java, src/test/java/tests/FormsTests/PracticeFormTest.java, src/test/java/utils/DateTimeUtils.java, src/test/java/utils/ReportUtils.java, src/test/java/utils/TestUtils.java
Applied the best practices from OpenWeather project)
=> [DF-45] Refactor the core classes

src/test/java/pages/BookStoreApplication/BookStorePage.java, src/test/java/tests/BookStoreApplicationTest/BookStoreApplicationTest.java
testBooksListChecking is added, 1 locator is changed
=> [DF-46] AT testBooksListChecking() is added

src/test/java/pages/BookStoreApplication/BookStorePage.java, src/test/java/testData/TestData.java, src/test/java/tests/BookStoreApplicationTest/BookStoreApplicationTest.java, src/test/java/tests/ElementsTests/CheckBoxTest.java
testSearchingBooksResult is added with dataprovider
=> [DF-47]_testSearchingBooksResults is added with dataprovider

src/test/java/base/BaseTest.java, src/test/java/pages/Elements/CheckBoxPage.java, src/test/java/tests/ElementsTests/CheckBoxTest.java, src/test/java/tests/ElementsTests/ElementsTest.java
added scrollByVisibleElement - this is why my test failed all the time.
Now it works)
=> [DF-48] Refactor testOneElementIsUnchecked

src/test/java/pages/Interactions/InteractionsPage.java, src/test/java/testData/TestData.java, src/test/java/tests/InteractionsTest.java
testInteractionsSubMenuLinksNavigateToCorrectPages added
=> testInteractionsSubMenuLinksNavigateToCorrectPages added

src/test/java/base/BaseTest.java, src/test/java/pages/Forms/FormsPage.java, src/test/java/pages/Interactions/InteractionsPage.java, src/test/java/pages/Interactions/SelectablePage.java, src/test/java/tests/FormsTests/FormsTest.java, src/test/java/tests/FormsTests/PracticeFormTest.java, src/test/java/tests/SelectableTest.java
added testNavigationSelectablePage()
code refactoring
=> added testNavigationSelectablePage()

src/test/java/pages/Elements/ButtonsPage.java, src/test/java/tests/ElementsTests/ButtonTest.java
testCheckingNamesButtons - https://fem22.atlassian.net/browse/DF-57?atlOrigin=eyJpIjoiYmRlZGEzMDI1Y2M5NGVlZjk4ODk3ZTY2YTgyMDhkZTIiLCJwIjoiaiJ9
testCheckingQuantityButtons - https://fem22.atlassian.net/browse/DF-58?atlOrigin=eyJpIjoiYmNlYzRmMDVmMTgyNGQ5NWI1YTdkNmFmZTNiZGE2ZDUiLCJwIjoiaiJ9
testCheckingMainHeader - https://fem22.atlassian.net/browse/DF-59?atlOrigin=eyJpIjoiNDViMTBhNzU4Y2MwNGI0OTllMzRjOGJiNTQwMGI5MjYiLCJwIjoiaiJ9
=> testCheckingNamesButtons_and_testCheckingQuantityButtons_and_testCheckingMainHeader

src/test/java/pages/Elements/CheckBoxPage.java, src/test/java/testData/TestData.java, src/test/java/tests/ElementsTests/CheckBoxTest.java
test_ExpandListWithAllCheckBoxes added
Also i added DataProvider info into TestData class for future refactor this test with DataProvider aproach.
=> [DF-61] Check title of CheckBoxes when expand the checkbox tree [Elements/CheckBox]

src/test/java/pages/BasePage.java, src/test/java/pages/Interactions/InteractionsPage.java, src/test/java/pages/Interactions/SelectablePage.java, src/test/java/testData/TestData.java, src/test/java/tests/SelectableTest.java
added testAllTabListElementsSelectable
[DF-63]-https://fem22.atlassian.net/jira/software/c/projects/DF/boards/1?modal=detail&selectedIssue=DF-63
=> [DF-63]AllTabListElementsSelectable[Interactions/Selectable]

src/test/java/pages/BasePage.java, src/test/java/pages/Elements/ButtonsPage.java, src/test/java/pages/Interactions/SortablePage.java, src/test/java/tests/InteractionTests/InteractionsTest.java, src/test/java/tests/InteractionTests/SortableTest.java
testReversWebElements - Jira - https://fem22.atlassian.net/browse/DF-66?atlOrigin=eyJpIjoiODVhNmVmZWYyNWNhNDg0NmIwYzBiNjRmNGE3YzcxMzIiLCJwIjoiaiJ9
=> [DF - 51] testReversWebElements [Interactions/Sortable]

src/test/java/pages/BasePage.java, src/test/java/pages/Interactions/SortablePage.java, src/test/java/tests/InteractionTests/SortableTest.java
testRandomElementGrid_ElementsCanBeSwapped - Jira - https://fem22.atlassian.net/browse/DF-67?atlOrigin=eyJpIjoiOTZjYmE5MzNlOTQ0NDU3ODk5NTIwNzMwY2Q4NmY2MDEiLCJwIjoiaiJ9
=> [DF - 67] testRandomElementGrid_ElementsCanBeSwapped [Interactions/Sortable] 

pom.xml, src/test/java/api/Root.java, src/test/java/pages/BookStoreApplication/BookStoreAPIPage.java, src/test/java/pages/HomePage.java, src/test/java/tests/BookStoreApplicationTest/BookStoreAPITest.java
test_API_HttpRequestResponse_IsbnNumber_BookDesigning_Evolvable_Web_APIs_With_ASP_NET - JIRA - https://fem22.atlassian.net/browse/DF-68?atlOrigin=eyJpIjoiMGY4MDViNGYyOTk3NDhjMWE4MDg0NDY1OTYwZWEyNjkiLCJwIjoiaiJ9
=> [DF - 68] test_API_HttpRequestResponse_IsbnNumber_BookDesigning_Evolvable_Web_APIs_With_ASP_NET [BookStoreApplication/BookStore]

src/test/java/pages/Widgets/WidgetsPage.java, src/test/java/tests/WidgetsTest/AccordianTest.java, src/test/java/tests/WidgetsTest/WidgetTest.java
1. https://fem22.atlassian.net/jira/software/c/projects/DF/boards/1?modal=detail&selectedIssue=DF-32
=> [DF-32]testURLAccordianPage[Widgets/Accordian]

src/test/java/tests/WidgetsTest/WidgetTest.java
1. https://fem22.atlassian.net/jira/software/c/projects/DF/boards/1?modal=detail&selectedIssue=DF-71
=> [DF-69]testURLWidgetsPage[Widgets]

src/test/java/api/ApiHelpers.java, src/test/java/api/model/Book.java, src/test/java/api/model/Root.java, src/test/java/tests/BookStoreApplicationTest/BookStoreAPITest.java
test_API_HttpRequestResponse_TitleOfAllBooks - Jira - https://fem22.atlassian.net/browse/DF-72?atlOrigin=eyJpIjoiZWJmNzE2YzJmNjhmNDc3Y2E0NTIwMmM3MjRhMDMyZWIiLCJwIjoiaiJ9
=> [DF - 72] test_API_HttpRequestResponse_TitleOfAllBooks [BookStoreApplication/BookStore]

src/test/java/pages/BasePage.java, src/test/java/pages/Interactions/SelectablePage.java, src/test/java/testData/TestData.java, src/test/java/tests/InteractionTests/SelectableTest.java
added testSelectAllTabsInGrid
added test Priority
renamed variables 
[DF-64]- https://fem22.atlassian.net/jira/software/c/projects/DF/boards/1?selectedIssue=DF-64
=> [DF-64]testSelectAllTabsInGrid[Interactions/Selectable]

src/test/java/pages/BasePage.java, src/test/java/tests/InteractionTests/SelectableTest.java
SelectableTest refactored
Variables changed
Priority deleted
[DF-76]-https://fem22.atlassian.net/jira/software/c/projects/DF/boards/1?modal=detail&selectedIssue=DF-76
=> [DF-76][RFSelectableTestclass][Interactions/Selectable]

src/test/java/base/BaseTest.java, src/test/java/pages/AlertsFramesWindows/AlertsFramesWindowsPage.java, src/test/java/pages/AlertsFramesWindows/BrowserWindowsPage.java, src/test/java/pages/AlertsFramesWindows/SamplePage.java, src/test/java/tests/AlertsFramesWindowTest/AlertsTest.java, src/test/java/tests/AlertsFramesWindowTest/BrowserWindowsTest.java, src/test/java/tests/AlertsFramesWindowsTest.java
testCheckH1TextAndURLInNewTab is added, new page and test classes are created
=> [DF-80]testCheckH1TextAndURLInNewTab[Alerts,Frames&Windows/BrowserWindows]

src/test/java/pages/Elements/LinksPage.java, src/test/java/tests/ElementsTests/LinksTest.java
[Jira DF-81](https://fem22.atlassian.net/jira/software/c/projects/DF/boards/1?modal=detail&selectedIssue=DF-27&assignee=5f55ddbde0d306007637cf1b)
=> [DF-81] testHomeLinkRedirection[Elements/Links]

src/test/java/pages/Elements/ButtonsPage.java, src/test/java/pages/Elements/LinksPage.java, src/test/java/testData/TestData.java, src/test/java/tests/ElementsTests/LinksTest.java
testCheckingResponseCodeAndNameAfterLinkIsClicked - JIRA - https://fem22.atlassian.net/browse/DF-84?atlOrigin=eyJpIjoiM2ZmYTQzZmZmN2JiNGY0Njk2YjQzMTU1Yjk3NmNiYTMiLCJwIjoiaiJ9
=> [DF-84]testCheckingResponseCodeAndNameAfterLinkIsClicked[Elements/Links]

src/test/java/pages/Interactions/DroppablePage.java, src/test/java/tests/InteractionTests/DroppableTest.java, src/test/java/tests/InteractionTests/InteractionsTest.java
added testNavigationDroppablePage
added page DroppableTest
[DF-85] - https://fem22.atlassian.net/jira/software/c/projects/DF/boards/1?modal=detail&selectedIssue=DF-85
=> [DF85]testNavigationDroppablePage[Interactions/Droppable]

src/test/java/pages/Widgets/WidgetsPage.java, src/test/java/tests/WidgetsTest/WidgetTest.java
add new test testWidgetsList
1. https://fem22.atlassian.net/jira/software/c/projects/DF/boards/1?modal=detail&selectedIssue=DF-78
=> [DF - 78]testWidgetsList[Widgets]

src/test/java/pages/BasePage.java, src/test/java/pages/HomePage.java, src/test/java/pages/Interactions/DroppablePage.java, src/test/java/pages/Interactions/InteractionsPage.java, src/test/java/tests/ElementsTests/LinksTest.java, src/test/java/tests/InteractionTests/DroppableTest.java
added testSimpleDrop()
changed Assert in testHomeLinkRedirection()
[DF-86]- https://fem22.atlassian.net/jira/software/c/projects/DF/boards/1?modal=detail&selectedIssue=DF-86
=> [DF86]testSimpleDrop[Interactions/Droppable]

src/test/java/pages/Interactions/SortablePage.java, src/test/java/tests/InteractionTests/SortableTest.java
testNavigationAndHeaderSortablePage - Jira - https://fem22.atlassian.net/browse/DF-87?atlOrigin=eyJpIjoiMjIzNmMyNTliNTkzNDkxYmFiZmE5NDlmOWI3NDFlMjciLCJwIjoiaiJ9
=> [DF87]testNavigationAndHeaderSortablePage[Interactions/Sortable] 

src/test/java/pages/BasePage.java, src/test/java/pages/Interactions/InteractionsPage.java, src/test/java/pages/Interactions/SortablePage.java
Refactor testReversWebElements - Jira - https://fem22.atlassian.net/browse/DF-88?atlOrigin=eyJpIjoiZDA0MzAxZWI4MTA0NDkyZThlMmUwOTlhZTIyNTliNjUiLCJwIjoiaiJ9
=> [DF-88] Refactor testReversWebElements[Interactions/Sortable] 

src/test/java/pages/BasePage.java, src/test/java/pages/Elements/CheckBoxPage.java, src/test/java/tests/ElementsTests/CheckBoxTest.java
Refactor testAllCheckBoxSelected - JIRA - https://fem22.atlassian.net/browse/DF-89?atlOrigin=eyJpIjoiOTc2ZWRlOGY0ZGIwNGNmY2I1OWMzNGMzOTMyODI5Y2YiLCJwIjoiaiJ9
=> [DF-89] Refactor testAllCheckBoxSelected [Elements/CheckBox]

src/test/java/pages/AlertsFramesWindows/AlertsPage.java, src/test/java/testData/TestData.java, src/test/java/tests/AlertsFramesWindowTest/AlertsTest.java, src/test/java/tests/BookStoreApplicationTest/BookStoreTest.java, src/test/java/tests/FormsTests/FormsTest.java, src/test/java/tests/HomePageTest.java, src/test/java/tests/InteractionTests/DroppableTest.java, src/test/java/tests/InteractionTests/SelectableTest.java
testCheckAlertOneClick is aded
=> [DF-90] testCheckAlertOneClick [Alerts,Frames&Windows/BrowserWindows]

src/test/java/pages/AlertsFramesWindows/AlertsPage.java, src/test/java/tests/AlertsFramesWindowTest/AlertsTest.java
DF93 testCheckOneClickAndWaitAlertText is aded
JIRA https://fem22.atlassian.net/browse/DF-93?atlOrigin=eyJpIjoiNTI4NTg0NDRjMTc4NDZlM2IwODM1ODBhMGJjZGFkMjQiLCJwIjoiaiJ9
=> [DF-93] testCheckOneClickAndWaitAlert [Alerts,Frames&Windows/Alerts]

src/test/java/tests/FormsTests/FormsTest.java, src/test/java/tests/FormsTests/PracticeFormTest.java, src/test/java/tests/InteractionTests/DroppableTest.java, src/test/java/tests/InteractionTests/SelectableTest.java, src/test/java/utils/ProjectConstants.java
Added ProjectConstants class
Refactoring classes, variables
=> [DF-95]RefactoringClassesAndVariables

pom.xml
Version 7.7.1 fix Vulnerabilities from version 7.6.1
https://mvnrepository.com/artifact/org.testng/testng
[TestNG](https://mvnrepository.com/artifact/org.testng/testng) » [7.6.1](https://mvnrepository.com/artifact/org.testng/testng/7.6.1)
Vulnerabilities | Direct vulnerabilities:CVE-2022-4065Vulnerabilities from dependencies:CVE-2022-41854CVE-2022-38752CVE-2022-38751CVE-2022-38750CVE-2022-25857
-- | --
Vulnerabilities	Direct vulnerabilities:
[CVE-2022-4065](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-4065)
Vulnerabilities from dependencies:
[CVE-2022-41854](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-41854)
[CVE-2022-38752](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-38752)
[CVE-2022-38751](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-38751) …
=> UPDATED TestNG to 7.7.1

src/test/java/pages/Elements/LinksPage.java, src/test/java/tests/ElementsTests/LinksTest.java
[DF - 96](https://fem22.atlassian.net/jira/software/c/projects/DF/boards/1?assignee=5f55ddbde0d306007637cf1b&modal=detail&selectedIssue=DF-96) hyperlink redirection on LinkPage
=> [DF-96] - HomDynamichyperlink redirection on LinkPage

src/test/java/tests/InteractionTests/SortableTest.java
Refactor testReversWebElements - Jira - https://fem22.atlassian.net/browse/DF-97?atlOrigin=eyJpIjoiMTY3MjgzYzlmZTdiNDRkNTkxZDUyMzQwN2FiMGRhYmUiLCJwIjoiaiJ9
=> [DF-97]Refactor  testReversWebElements[Interactions/Sortable]

src/test/java/pages/AlertsFramesWindows/AlertsPage.java, src/test/java/pages/BasePage.java, src/test/java/tests/AlertsFramesWindowTest/AlertsTest.java
testCheckTextAndConfirmThierAlert is added + renaming old methods in AlertPage/AlertTest
Jira https://fem22.atlassian.net/jira/software/c/projects/DF/boards/1?modal=detail&selectedIssue=DF-94
=> [DF-94] testCheckTextAndConfirmThirdAlert[Alerts, frames&Windows/Alerts]

src/test/java/pages/AlertsFramesWindows/AlertsPage.java, src/test/java/pages/BasePage.java, src/test/java/tests/AlertsFramesWindowTest/AlertsTest.java
testCheckTextAndDismissAlert is added
JIRA https://fem22.atlassian.net/jira/software/c/projects/DF/boards/1?modal=detail&selectedIssue=DF-92
=> [DF-99] testCheckTextAndDismissThirdAlert [Alerts,frames&windows/Alerts]

src/test/java/pages/Elements/LinksPage.java, src/test/java/tests/ElementsTests/LinksTest.java
[DF-100](https://fem22.atlassian.net/jira/software/c/projects/DF/boards/1?assignee=5f55ddbde0d306007637cf1b&modal=detail&selectedIssue=DF-100)
=> [DF-100] - List of API calls

src/test/java/pages/AlertsFramesWindows/AlertsPage.java, src/test/java/pages/BasePage.java, src/test/java/tests/AlertsFramesWindowTest/AlertsTest.java
testEnterTextAndConfirmForthAlert and testCheckTextAndConfirmForthAlert are added
testCheckTextAndConfirmForthAlert is almost the same as previous ones, only other names. 
JIRA https://fem22.atlassian.net/jira/software/c/projects/DF/boards/1?modal=detail&selectedIssue=DF-101
JIRA https://fem22.atlassian.net/jira/software/c/projects/DF/boards/1?modal=detail&selectedIssue=DF-102
=> [DF-101/102]testEnterTextAndConfirmAlert [Alerts,frames&windows/Alerts]

src/test/java/pages/Interactions/InteractionsPage.java, src/test/java/pages/Interactions/ResizablePage.java, src/test/java/tests/InteractionTests/ResizableTest.java, src/test/java/utils/ProjectConstants.java
added testNavigationResizablePage
added class ResizableTest
[DF-103] - https://fem22.atlassian.net/jira/software/c/projects/DF/boards/1?modal=detail&selectedIssue=DF-103
=> [DF-103]testNavigationResizablePage[Interactions\Selectable]

src/test/java/pages/Interactions/ResizablePage.java, src/test/java/tests/InteractionTests/ResizableTest.java
added testResizableBox
[DF-104]https://fem22.atlassian.net/jira/software/c/projects/DF/boards/1?modal=detail&selectedIssue=DF-104
=> [DF-104]testResizableBox[Interaction/Resizable]

src/test/java/pages/Interactions/ResizablePage.java, src/test/java/tests/InteractionTests/ResizableTest.java
added testResizablePlain
[DF-105]https://fem22.atlassian.net/jira/software/c/projects/DF/boards/1?modal=detail&selectedIssue=DF-105
=> [DF-105]testResizablePlain[Interactions/Resizable]

src/test/java/pages/AlertsFramesWindows/AlertsPage.java, src/test/java/pages/BasePage.java, src/test/java/tests/AlertsFramesWindowTest/AlertsTest.java
testDismissForthAlert is added
JIRA https://fem22.atlassian.net/browse/DF-108
=> [DF-108] testDismissForthALert [Alerts, frames & windows/Alerts]

src/test/java/pages/Interactions/DroppablePage.java, src/test/java/tests/InteractionTests/DroppableTest.java
testActualTabsOnTheDroppablePage - Jira - https://fem22.atlassian.net/browse/DF-109?atlOrigin=eyJpIjoiMzRiMjczYzc1YTQyNDIwMzkwYWVjNTZhMmJhOGMxYmIiLCJwIjoiaiJ9
Hello team, this is my test, I am checking that the title of the tabs matches the requirement.
=> [RF-109]testActualTabsOnTheDroppablePage[Interactions/Droppable]

src/test/java/base/BaseTest.java, src/test/java/pages/BasePage.java, src/test/java/tests/AlertsFramesWindowTest/AlertsTest.java, src/test/resources/regression.xml, src/test/resources/smoke.xml, src/test/resources/testng.xml
I learned how to create any Test Suite with custom Tests as an example added Smoke suite.(using Clasess and Methods way)
Regression suite it is an example how to use groups in TestNG.xml but for now it does't works...
In the future we can use different ways. First one is the simple one.(select class > select method)
=> added Smoke suite into TestNG

src/test/java/pages/Widgets/ProgressBarPage.java, src/test/java/pages/Widgets/WidgetsPage.java, src/test/java/tests/WidgetsTest/ProgressBarTest.java
testCheckBackgroundColorProgressBar - Jira - https://fem22.atlassian.net/browse/DF-114?atlOrigin=eyJpIjoiNWI3N2FmODQ1OWY5NGRjM2E2NWJiN2Q5MGNhNjg4M2IiLCJwIjoiaiJ9
The thet test checks the background color progress bar.
=> [DF-114]testCheckBackgroundColorProgressBar[Widgets/ProgressBar]

src/test/java/pages/Elements/WebTablesPage.java, src/test/java/tests/ElementsTests/WebTablesTest.java
https://fem22.atlassian.net/jira/software/c/projects/DF/boards/1?modal=detail&selectedIssue=DF-115
=> [DF-115] test_CheckEditEmail added [Elements/Web Tables]

src/test/java/pages/Widgets/ProgressBarPage.java, src/test/java/tests/WidgetsTest/ProgressBarTest.java
testCheckWhatTheButtonChangesTheName -  Jira - https://fem22.atlassian.net/browse/DF-116?atlOrigin=eyJpIjoiZDdmZjY4ZGZmYjAzNDY3NDgwZGY1YWEzZWY5NzA2N2MiLCJwIjoiaiJ9
This test tests a button that changes its name three times.
=> [DF-116]testCheckWhatTheButtonChangesTheName[Widgets/ProgressBar]

src/test/java/pages/Elements/WebTablesPage.java, src/test/java/tests/ElementsTests/WebTablesTest.java
https://fem22.atlassian.net/jira/software/c/projects/DF/boards/1?modal=detail&selectedIssue=DF-117
=> [DF-115] REFACTOR test_CheckEditEmail [Elements/Web Tables]

src/test/java/pages/Elements/WebTablesPage.java, src/test/java/tests/ElementsTests/WebTablesTest.java
https://fem22.atlassian.net/jira/software/c/projects/DF/boards/1?modal=detail&selectedIssue=DF-118
=> [DF-118] test_DeleteUser added [Elements/WebTables]

src/test/java/pages/AlertsFramesWindows/AlertsFramesWindowsPage.java, src/test/java/pages/AlertsFramesWindows/ModalDialogsPage.java, src/test/java/pages/BookStoreApplication/LoginPage.java, src/test/java/tests/AlertsFramesWindowTest/ModalDialogsTest.java
one small RF: method clickLoginButton()/LoginPage is changed
testCheckSmallModalDialogText()/ModalDialogsTest is added
Jira https://fem22.atlassian.net/browse/DF-120
=> [DF-120] testCheckSmallModalDialogText [Alerts, Frames & Windows/Modal Dialogs]

pom.xml, src/test/java/tests/BookStoreApplicationTest/BookStoreAPITest.java
Rest Assured in POM is added, testCheckGetBooksAPIRequest is added
JIRA https://fem22.atlassian.net/browse/DF-124
=> [DF-124] RF POM/ testCheckGetBooksAPIRequest is added[Book Store Application/Book Store API]

src/test/java/api/model/Book.java, src/test/java/pages/BookStoreApplication/BookStorePage.java, src/test/java/testData/TestData.java, src/test/java/tests/BookStoreApplicationTest/BookStoreAPITest.java
testCheckGetBooksAPIRequestV2 is added
JIRA https://fem22.atlassian.net/browse/DF-125
=> [DF-125] testCheckGetBooksAPIRequestV2 [Book Store Applicaton/Book Store API]

src/test/java/pages/AlertsFramesWindows/ModalDialogsPage.java, src/test/java/tests/AlertsFramesWindowTest/ModalDialogsTest.java
testCheckLargeModalBoxText is added
JIRA https://fem22.atlassian.net/browse/DF-121
=> [DF-121] testCheckLargeModalBoxText [Alerts, Frames & Windows/ Modal Dialogs ]

src/test/java/pages/BasePage.java, src/test/java/pages/BookStoreApplication/LoginPage.java, src/test/java/service/ConfProperties.java, src/test/java/service/LoggingConfProperties.java, src/test/java/tests/BookStoreApplicationTest/LoginTest.java, src/test/java/tests/BookStoreApplicationTest/ProfileTest.java, src/test/java/tests/ElementsTests/CheckBoxTest.java, src/test/java/tests/InteractionTests/ResizableTest.java, src/test/resources/conf.properties
RF remove Username and Password from the code to external file conf.properties
Security pattern of the code that we should follow in the future.
=> [DF-127] SecurityRefactor_RemoveUserNameAndPassword 

src/test/java/pages/BookStoreApplication/BookStorePage.java, src/test/java/tests/BookStoreApplicationTest/BookStoreAPITest.java, src/test/java/tests/FormsTests/PracticeFormTest.java
RF testCheckGetBooksAPIRequestV2:  waiter is added into the method
JIRA https://fem22.atlassian.net/browse/DF-129
=> RF testCheckGetBooksAPIRequestV2

src/test/java/tests/BookStoreApplicationTest/BookStoreAPITest.java
added testFindBookByIsbnAPIRequest
[DF-128] - https://fem22.atlassian.net/jira/software/c/projects/DF/boards/1?modal=detail&selectedIssue=DF-128
=> [DF-128]testFindBookByIsbnAPIRequest<MaxIasko>

src/test/java/tests/BookStoreApplicationTest/BookStoreAPITest.java
Added testCreateUserApiRequestResponse
[DF-131-]https://fem22.atlassian.net/jira/software/c/projects/DF/boards/1?modal=detail&selectedIssue=DF-131
=> [DF-131]testCreateUserApiRequestResponse<MaxIasko>

src/test/java/tests/BookStoreApplicationTest/BookStoreAPITest.java
refactoring testFindBookByIsbnAPIRequest
added queryParams(Map.of("isbn", isbn)
[DF-130] - https://fem22.atlassian.net/jira/software/c/projects/DF/boards/1?modal=detail&selectedIssue=DF-130
=> [DF-130]RF_testFindBookByIsbnAPIRequest<MaxIasko>

src/test/java/tests/ElementsTests/CheckBoxTest.java, src/test/java/tests/retrytest/IRetryAnalyzer.java, src/test/java/tests/retrytest/Retry.java
added new feature to the project)
We will see how it works.
Remove ignore from test_ExpandListWithAllCheckBoxes and added to this test new feature "retry"
=> IRetryAnalyzer added

src/test/java/pages/Elements/WebTablesPage.java, src/test/java/tests/ElementsTests/WebTablesTest.java
JIRA: https://fem22.atlassian.net/jira/software/c/projects/DF/boards/1?modal=detail&selectedIssue=DF-132
=> [DF-132] testTablePresentOnly5Rows [Elements/WebTables]

.github/workflows/ci.yml
=> More detailed Logs 

src/test/java/pages/BasePage.java, src/test/java/pages/Elements/WebTablesPage.java, src/test/java/tests/ElementsTests/WebTablesTest.java
JIRA - https://fem22.atlassian.net/jira/software/c/projects/DF/boards/1?modal=detail&selectedIssue=DF-133
=> [DF-133] testPreviousButtonIsEnabled [Elements/WebTables]

src/test/java/pages/AlertsFramesWindows/ModalDialogsPage.java, src/test/java/tests/AlertsFramesWindowTest/ModalDialogsTest.java
testCloseButtonSmallModalDialogBox and testCloseButtonLargeModalDialogBox are added
JIRA https://fem22.atlassian.net/browse/DF-135
JIRA https://fem22.atlassian.net/browse/DF-136
=> [DF-135]testCloseButtonSmallModalDialogBox is added [Alerts,Frames &Windows]/{Modal Dialogs]

src/test/java/base/BaseTest.java, src/test/java/pages/BasePage.java, src/test/java/pages/Elements/BrokenLinks_ImagesPage.java, src/test/java/pages/Elements/ElementsPage.java, src/test/java/tests/ElementsTests/BrokenLinks_ImagesTest.java
JIRA - https://fem22.atlassian.net/jira/software/c/projects/DF/boards/1?modal=detail&selectedIssue=DF-137
=> [DF - 137] testURLAndHeaderOfBrokenLinks_ImagesPage [Elements/BrokenLinks_Images]

infra/db/sql/init.sql, infra/docker-compose.yaml, pom.xml, src/test/java/base/BaseUtils.java, src/test/resources/healenium.properties
Healenium improves stability of Selenium-based test cases, handling changes of updated web elements.
https://github.com/healenium/healenium-web/blob/master/README.md
for now it doesn't works properly. but we kept this code for the future.)
=> Healenium added

.github/workflows/ci.yml, pom.xml
Azul Zulu, on the other hand, is designed to provide high performance, scalability, and low latency for Java applications. It includes advanced features such as pauseless garbage collection and class data sharing, and is optimized for specific workloads such as microservices and cloud deployments.
during Update select Azul Zulu Java 17.(it has support until 2029)
=> upgrade to Java 17
